<?php
$q=trim($_GET['q']??''); $edit=(int)($_GET['edit']??0); $editing=null;
if($edit){$st=$pdo->prepare("SELECT * FROM {$cfg['table']} WHERE id=?");$st->execute([$edit]);$editing=$st->fetch();}
$where='';$params=[];
if($q){$parts=[];foreach($cfg['search'] as $c){$parts[]="$c LIKE ?";$params[]="%$q%";}$where=' WHERE '.implode(' OR ',$parts);}
$st=$pdo->prepare("SELECT * FROM {$cfg['table']}$where ORDER BY id DESC LIMIT 200");$st->execute($params);$rows=$st->fetchAll();
$clients=$pdo->query("SELECT id,name FROM clients ORDER BY name")->fetchAll();
$visible=array_slice($cfg['fields'],0,6);
?>
<div class="page-head"><div><span class="eyebrow">GESTÃO</span><h1><?=e($cfg['title'])?></h1><p>Cadastre, consulte e acompanhe informações do módulo.</p></div><button class="btn primary" onclick="openModal()">+ Novo registro</button></div>
<div class="panel table-panel"><div class="toolbar"><form class="search-form"><input type="hidden" name="module" value="<?=e($module)?>"><input name="q" placeholder="Pesquisar..." value="<?=e($q)?>"><button class="btn">Buscar</button></form><span class="record-count"><?=count($rows)?> registros</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>#</th><?php foreach($visible as $f):?><th><?=e($f['label'])?></th><?php endforeach;?><th>Ações</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td class="muted">#<?=$r['id']?></td><?php foreach($visible as $f): $v=$r[$f['name']]??''; ?><td><?php if(in_array($f['name'],['status','stage','priority'])):?><span class="badge <?=badgeClass((string)$v)?>"><?=e($v)?></span><?php elseif(in_array($f['name'],['value','amount','budget'])):?><b><?=money($v)?></b><?php elseif($f['name']==='client_id'): $cn='—'; foreach($clients as $c)if($c['id']==$v)$cn=$c['name']; echo e($cn); else: echo e($v?:'—'); endif;?></td><?php endforeach;?><td><div class="actions"><a class="icon-btn" href="?module=<?=e($module)?>&edit=<?=$r['id']?>" title="Editar">✎</a><form method="post" onsubmit="return confirm('Excluir este registro?')"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="icon-btn danger-text" title="Excluir">×</button></form></div></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="<?=count($visible)+2?>" class="empty">Nenhum registro encontrado.</td></tr><?php endif;?></tbody></table></div></div>
<div class="modal <?=$editing?'show':''?>" id="recordModal"><div class="modal-card"><div class="modal-head"><div><span class="eyebrow"><?=$editing?'EDIÇÃO':'NOVO REGISTRO'?></span><h2><?=$editing?'Editar':'Cadastrar'?> <?=e(rtrim($cfg['title'],'s'))?></h2></div><button onclick="closeModal()">×</button></div><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="id" value="<?=$editing['id']??''?>"><?php foreach($cfg['fields'] as $f): $name=$f['name'];$type=$f['type']??'text';$val=$editing[$name]??'';?><label class="<?=$type==='textarea'?'span-2':''?>"><?=e($f['label'])?><?php if($type==='select'):?><select name="<?=e($name)?>" <?=$f['required']??false?'required':''?>><?php foreach($f['options'] as $o):?><option <?=$val===$o?'selected':''?>><?=e($o)?></option><?php endforeach;?></select><?php elseif($type==='client'):?><select name="<?=e($name)?>"><option value="">Sem cliente</option><?php foreach($clients as $c):?><option value="<?=$c['id']?>" <?=$val==$c['id']?'selected':''?>><?=e($c['name'])?></option><?php endforeach;?></select><?php elseif($type==='textarea'):?><textarea name="<?=e($name)?>" rows="4"><?=e($val)?></textarea><?php else:?><input type="<?=e($type)?>" name="<?=e($name)?>" value="<?=e($val)?>" <?=isset($f['step'])?'step="'.e($f['step']).'"':''?> <?=$f['required']??false?'required':''?>><?php endif;?></label><?php endforeach;?><div class="modal-actions span-2"><button type="button" class="btn" onclick="closeModal()">Cancelar</button><button class="btn primary">Salvar registro</button></div></form></div></div>
<?php if($editing):?><script>window.addEventListener('DOMContentLoaded',()=>openModal())</script><?php endif;?>
