<?php
$clientCount=(int)$pdo->query("SELECT COUNT(*) FROM clients")->fetchColumn();
$leadCount=(int)$pdo->query("SELECT COUNT(*) FROM leads WHERE status NOT IN ('Descartado','Convertido')")->fetchColumn();
$pipeline=(float)$pdo->query("SELECT COALESCE(SUM(value),0) FROM opportunities WHERE stage NOT IN ('Ganho','Perdido')")->fetchColumn();
$won=(float)$pdo->query("SELECT COALESCE(SUM(value),0) FROM opportunities WHERE stage='Ganho'")->fetchColumn();
$receita=(float)$pdo->query("SELECT COALESCE(SUM(amount),0) FROM finance WHERE type='Receita' AND status='Pago'")->fetchColumn();
$despesa=(float)$pdo->query("SELECT COALESCE(SUM(amount),0) FROM finance WHERE type='Despesa' AND status='Pago'")->fetchColumn();
$tasks=$pdo->query("SELECT * FROM tasks WHERE status NOT IN ('Concluída','Cancelada') ORDER BY due_date IS NULL,due_date LIMIT 6")->fetchAll();
$opps=$pdo->query("SELECT o.*,c.name client_name FROM opportunities o LEFT JOIN clients c ON c.id=o.client_id ORDER BY o.created_at DESC LIMIT 6")->fetchAll();
$stages=$pdo->query("SELECT stage,COUNT(*) qtd,COALESCE(SUM(value),0) total FROM opportunities GROUP BY stage")->fetchAll();
?>
<div class="page-head"><div><span class="eyebrow">PAINEL EXECUTIVO</span><h1>Boa noite, <?=e(explode(' ',$_SESSION['user']['name'])[0])?>.</h1><p>Acompanhe vendas, operação e relacionamento em tempo real.</p></div><a class="btn primary" href="?module=oportunidades">+ Nova oportunidade</a></div>
<div class="stats-grid"><div class="stat-card"><span>Clientes</span><b><?=$clientCount?></b><small>base cadastrada</small></div><div class="stat-card"><span>Leads ativos</span><b><?=$leadCount?></b><small>em prospecção</small></div><div class="stat-card"><span>Pipeline aberto</span><b><?=money($pipeline)?></b><small>potencial comercial</small></div><div class="stat-card accent"><span>Vendas ganhas</span><b><?=money($won)?></b><small>oportunidades fechadas</small></div></div>
<div class="grid-2"><div class="panel"><div class="panel-head"><div><h3>Funil comercial</h3><p>Distribuição atual das oportunidades</p></div><a href="?module=oportunidades">Ver pipeline</a></div><div class="bars"><?php $max=max(array_column($stages,'total')?:[1]); foreach($stages as $s):?><div class="bar-row"><div><span><?=e($s['stage'])?></span><b><?=money($s['total'])?></b></div><div class="bar-track"><i style="width:<?=max(4,($s['total']/$max)*100)?>%"></i></div></div><?php endforeach;?></div></div>
<div class="panel"><div class="panel-head"><div><h3>Resumo financeiro</h3><p>Movimentações pagas</p></div><a href="?module=financeiro">Abrir financeiro</a></div><div class="finance-kpis"><div><span>Receitas</span><b class="positive"><?=money($receita)?></b></div><div><span>Despesas</span><b class="negative"><?=money($despesa)?></b></div><div><span>Resultado</span><b><?=money($receita-$despesa)?></b></div></div><div class="health"><span>Saúde operacional</span><strong><?=($receita-$despesa)>=0?'Positiva':'Atenção'?></strong></div></div></div>
<div class="grid-2"><div class="panel"><div class="panel-head"><div><h3>Próximas tarefas</h3><p>Prioridades da equipe</p></div><a href="?module=tarefas">Todas</a></div><div class="simple-list"><?php foreach($tasks as $t):?><div><span class="check">○</span><div><b><?=e($t['title'])?></b><small><?=e($t['priority'])?> • <?=e($t['due_date']?:'Sem prazo')?></small></div><span class="badge <?=badgeClass($t['status'])?>"><?=e($t['status'])?></span></div><?php endforeach;?><?php if(!$tasks):?><p class="empty">Nenhuma tarefa pendente.</p><?php endif;?></div></div>
<div class="panel"><div class="panel-head"><div><h3>Oportunidades recentes</h3><p>Negócios movimentados</p></div><a href="?module=oportunidades">Todas</a></div><div class="simple-list"><?php foreach($opps as $o):?><div><div class="avatar square">D</div><div><b><?=e($o['title'])?></b><small><?=e($o['client_name']?:'Sem cliente')?> • <?=money($o['value'])?></small></div><span class="badge <?=badgeClass($o['stage'])?>"><?=e($o['stage'])?></span></div><?php endforeach;?></div></div></div>
