<?php
if($_SERVER['REQUEST_METHOD']==='POST'){
 csrf_check(); $action=$_POST['action']??'save';
 if($action==='toggle'){$id=(int)$_POST['id'];$pdo->prepare('UPDATE users SET active=1-active WHERE id=?')->execute([$id]);flash('success','Status do usuário atualizado.');redirect('?module=usuarios');}
 $id=(int)($_POST['id']??0);$name=trim($_POST['name']??'');$email=trim($_POST['email']??'');$role=$_POST['role']??'Vendas';$pass=$_POST['password']??'';
 if($id){ if($pass){$pdo->prepare('UPDATE users SET name=?,email=?,role=?,password_hash=? WHERE id=?')->execute([$name,$email,$role,password_hash($pass,PASSWORD_DEFAULT),$id]);}else{$pdo->prepare('UPDATE users SET name=?,email=?,role=? WHERE id=?')->execute([$name,$email,$role,$id]);}}
 else{$pdo->prepare('INSERT INTO users(name,email,password_hash,role,active) VALUES(?,?,?,?,1)')->execute([$name,$email,password_hash($pass?:'Dream@123',PASSWORD_DEFAULT),$role]);}
 flash('success','Usuário salvo com sucesso.');redirect('?module=usuarios');
}
$users=$pdo->query('SELECT * FROM users ORDER BY id DESC')->fetchAll();
?>
<div class="page-head"><div><span class="eyebrow">ACESSOS</span><h1>Usuários e permissões</h1><p>Gerencie perfis de Administrador, Gerente, Vendas, Suporte e Financeiro.</p></div><button class="btn primary" onclick="openModal()">+ Novo usuário</button></div><div class="panel table-panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Usuário</th><th>E-mail</th><th>Perfil</th><th>Status</th><th>Último acesso</th><th>Ações</th></tr></thead><tbody><?php foreach($users as $u):?><tr><td><b><?=e($u['name'])?></b></td><td><?=e($u['email'])?></td><td><span class="badge info"><?=e($u['role'])?></span></td><td><span class="badge <?=$u['active']?'success':'danger'?>"><?=$u['active']?'Ativo':'Inativo'?></span></td><td><?=e($u['last_login']?:'Nunca')?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$u['id']?>"><button class="btn small"><?=$u['active']?'Desativar':'Ativar'?></button></form></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="modal" id="recordModal"><div class="modal-card"><div class="modal-head"><div><span class="eyebrow">NOVO ACESSO</span><h2>Cadastrar usuário</h2></div><button onclick="closeModal()">×</button></div><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><label>Nome<input name="name" required></label><label>E-mail<input type="email" name="email" required></label><label>Perfil<select name="role"><option>Administrador</option><option>Gerente</option><option>Vendas</option><option>Suporte</option><option>Financeiro</option></select></label><label>Senha<input type="password" name="password" required></label><div class="modal-actions span-2"><button type="button" class="btn" onclick="closeModal()">Cancelar</button><button class="btn primary">Criar usuário</button></div></form></div></div>
