<?php require_once __DIR__.'/functions.php'; ?>
<!doctype html><html lang="pt-br"><head><link rel="icon" type="image/png" href="assets/favicon.png"><link rel="shortcut icon" href="assets/favicon.png"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title??'Dreamlast PDV')?></title><link rel="stylesheet" href="assets/css/app.css?v=4.0.0"></head><body>
<?php if(isLogged()): ?>
<header class="topbar"><div class="brand"><span class="brand-mark">D</span><div><strong>Dreamlast</strong><small>PDV Pro v4</small></div></div><div class="top-actions"><span><?=e($_SESSION['user']['name'])?> · <?=e(ucfirst(role()))?></span><a class="btn ghost" href="index.php?page=logout">Sair</a></div></header>
<div class="layout"><aside class="sidebar"><nav>
<a href="index.php?page=dashboard">▦ Dashboard</a><?php if(can('pos')):?><a class="primary-nav" href="index.php?page=pos">◉ Frente de Caixa</a><?php endif;?><?php if(can('quotes')):?><a href="index.php?page=quotes">◇ Orçamentos</a><?php endif;?><?php if(can('products')):?><a href="index.php?page=products">□ Produtos</a><?php endif;?><a href="index.php?page=customers">♙ Clientes</a><?php if(can('suppliers')):?><a href="index.php?page=suppliers">♜ Fornecedores</a><?php endif;?><?php if(can('purchases')):?><a href="index.php?page=purchases">⇩ Compras</a><?php endif;?><a href="index.php?page=sales">🧾 Vendas</a><?php if(can('returns')):?><a href="index.php?page=returns">↩ Devoluções</a><?php endif;?><a href="index.php?page=cash">▣ Caixa</a><?php if(can('finance')):?><a href="index.php?page=finance">$ Financeiro</a><?php endif;?><?php if(can('inventory')):?><a href="index.php?page=inventory">▤ Inventário</a><?php endif;?><?php if(can('reports')):?><a href="index.php?page=reports">⌁ Relatórios</a><?php endif;?><?php if(isAdmin()): ?><a href="index.php?page=audit">☷ Auditoria</a><a href="index.php?page=users">♟ Usuários</a><a href="index.php?page=settings">⚙ Configurações</a><?php endif; ?>
</nav></aside><main class="content">
<?php if($m=flash('success')):?><div class="alert success"><?=e($m)?></div><?php endif;?><?php if($m=flash('error')):?><div class="alert error"><?=e($m)?></div><?php endif;?>
<?php endif; ?>
