<?php
requirePermission('products');
if($_SERVER['REQUEST_METHOD']==='POST'){ checkCsrf(); $action=$_POST['action']??'';
 if($action==='save'){
  $id=(int)($_POST['id']??0);$barcode=trim($_POST['barcode']??'');$barcode=$barcode!==''?$barcode:null;
  $data=[trim($_POST['sku']),$barcode,trim($_POST['name']),trim($_POST['brand']??''),trim($_POST['category']),trim($_POST['unit']??'UN'),trim($_POST['ncm']??''),str_replace(',','.',$_POST['cost']),str_replace(',','.',$_POST['price']),(int)$_POST['stock'],(int)$_POST['min_stock'],trim($_POST['location']??'')];
  try{
   if($id){$old=$pdo->prepare('SELECT stock FROM products WHERE id=?');$old->execute([$id]);$oldStock=(int)$old->fetchColumn();$st=$pdo->prepare('UPDATE products SET sku=?,barcode=?,name=?,brand=?,category=?,unit=?,ncm=?,cost=?,price=?,stock=?,min_stock=?,location=? WHERE id=?');$st->execute([...$data,$id]);$diff=$data[9]-$oldStock;if($diff!==0)$pdo->prepare('INSERT INTO stock_movements(product_id,user_id,type,quantity,reference,notes) VALUES(?,? ,"adjustment",?,"PRODUCT-EDIT","Alteração pelo cadastro de produto")')->execute([$id,$_SESSION['user']['id'],$diff]);audit($pdo,'update','product',$id,'Produto atualizado');}
   else{$st=$pdo->prepare('INSERT INTO products(sku,barcode,name,brand,category,unit,ncm,cost,price,stock,min_stock,location) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');$st->execute($data);$id=$pdo->lastInsertId();if($data[9]>0)$pdo->prepare('INSERT INTO stock_movements(product_id,user_id,type,quantity,reference,notes) VALUES(?,? ,"adjustment",?,"INITIAL","Estoque inicial")')->execute([$id,$_SESSION['user']['id'],$data[9]]);audit($pdo,'create','product',$id,'Produto cadastrado');}
   flash('success','Produto salvo com sucesso.');
  }catch(Throwable $e){flash('error',str_contains($e->getMessage(),'Duplicate')?'SKU ou código de barras já cadastrado.':$e->getMessage());}
  redirect('index.php?page=products');
 }
 if($action==='toggle'){ $id=(int)$_POST['id'];$pdo->prepare('UPDATE products SET active=1-active WHERE id=?')->execute([$id]);audit($pdo,'toggle','product',$id,'Status do produto alterado');redirect('index.php?page=products'); }
}
$edit=null;if(isset($_GET['edit'])){$st=$pdo->prepare('SELECT * FROM products WHERE id=?');$st->execute([(int)$_GET['edit']]);$edit=$st->fetch();}
$q=trim($_GET['q']??'');$st=$pdo->prepare('SELECT * FROM products WHERE name LIKE ? OR sku LIKE ? OR barcode LIKE ? OR brand LIKE ? ORDER BY id DESC');$st->execute(["%$q%","%$q%","%$q%","%$q%"]);$rows=$st->fetchAll();
$title='Produtos';require __DIR__.'/../../includes/header.php';?>
<div class="page-head"><div><h1>Produtos e estoque</h1><p>Cadastro completo, código de barras, localização e saldo.</p></div></div>
<div class="grid two"><section class="panel"><h2><?=$edit?'Editar produto':'Novo produto'?></h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=$edit['id']??0?>"><label>SKU<div class="input-action"><input name="sku" id="skuInput" required value="<?=e($edit['sku']??'')?>"><button type="button" class="btn" id="generateSku">Gerar</button></div></label><label>Código de barras<div class="input-action"><input name="barcode" data-barcode-input value="<?=e($edit['barcode']??'')?>" autocomplete="off" placeholder="Bipe, digite ou use a câmera"><button type="button" class="btn camera-btn" data-scan-barcode>📷 Abrir câmera</button></div><small class="field-help">Compatível com leitor USB/Bluetooth e câmera.</small></label><label class="span2">Nome<input name="name" required value="<?=e($edit['name']??'')?>"></label><label>Marca<input name="brand" value="<?=e($edit['brand']??'')?>"></label><label>Categoria<input name="category" value="<?=e($edit['category']??'Geral')?>"></label><label>Unidade<input name="unit" value="<?=e($edit['unit']??'UN')?>" placeholder="UN, KG, CX..."></label><label>NCM<input name="ncm" value="<?=e($edit['ncm']??'')?>"></label><label>Custo<input name="cost" type="number" step="0.01" min="0" value="<?=e($edit['cost']??'0')?>"></label><label>Preço de venda<input name="price" type="number" step="0.01" min="0" required value="<?=e($edit['price']??'0')?>"></label><label>Estoque atual<input name="stock" type="number" min="0" required value="<?=e($edit['stock']??'0')?>"></label><label>Estoque mínimo<input name="min_stock" type="number" min="0" required value="<?=e($edit['min_stock']??'5')?>"></label><label class="span2">Localização no estoque<input name="location" placeholder="Ex.: Corredor A / Prateleira 2" value="<?=e($edit['location']??'')?>"></label><div class="span2 product-tools"><strong>Atalhos de cadastro</strong><span>Use o leitor físico diretamente no campo Código de barras ou clique em 📷 Abrir câmera.</span></div><div class="span2 actions"><button class="btn primary">Salvar produto</button><?php if($edit):?><a class="btn" href="index.php?page=products">Cancelar</a><?php endif;?></div></form></section>
<section class="panel"><form class="search"><input name="q" placeholder="Buscar nome, marca, SKU ou código..." value="<?=e($q)?>"><button class="btn">Buscar</button></form><div class="table-wrap"><table><thead><tr><th>Produto</th><th>Código</th><th>Preço</th><th>Estoque</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><strong><?=e($r['name'])?></strong><small><?=e($r['brand'])?><?= $r['brand']?' · ':'' ?><?=e($r['sku'])?> · <?=e($r['category'])?></small></td><td><?=e($r['barcode']?:'-')?></td><td><?=money($r['price'])?></td><td><span class="badge <?=$r['stock']<=$r['min_stock']?'danger':'ok'?>"><?=$r['stock']?> <?=e($r['unit'])?></span><small><?=e($r['location']?:'Sem localização')?></small></td><td><?=$r['active']?'Ativo':'Inativo'?></td><td class="row-actions"><a href="index.php?page=products&edit=<?=$r['id']?>">Editar</a><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="link-btn"><?=$r['active']?'Desativar':'Ativar'?></button></form></td></tr><?php endforeach;?></tbody></table></div></section></div>
<?php require __DIR__.'/../../includes/footer.php';?>
