"""Playwright + Chromium: browser regressions of this local project only.
pip install playwright; playwright install chromium
Optional AXE_PATH injects a locally downloaded axe-core script in QA contexts.
"""
import asyncio, json, os, unittest
from pathlib import Path
from playwright.async_api import async_playwright

BASE=os.environ.get('PRATOPERTO_TEST_URL','http://127.0.0.1:8090/').rstrip('/')+'/'
ARTIFACTS=Path(__file__).resolve().parents[1]/'replica'/'clone-screens'
class Browser(unittest.IsolatedAsyncioTestCase):
 async def asyncSetUp(self):
  self.p=await async_playwright().start()
  executable=os.environ.get('CHROMIUM_PATH')
  self.browser=await self.p.chromium.launch(executable_path=executable,args=['--no-sandbox','--disable-dev-shm-usage','--disable-gpu'])
  self.context=await self.browser.new_context(viewport={'width':1440,'height':1000},bypass_csp=bool(os.environ.get('AXE_PATH')))
  self.page=await self.context.new_page();self.errors=[]
  self.page.on('pageerror',lambda error:self.errors.append(str(error)))
  self.page.on('response',lambda response:self.errors.append('HTTP '+str(response.status)+' '+response.url) if response.status>=500 else None)
  await self.page.goto(BASE)
  await self.page.get_by_role('heading',name='Hoje combina').wait_for()
 async def asyncTearDown(self):
  errors=self.errors[:]
  await self.browser.close();await self.p.stop()
  self.assertEqual(errors,[],'Browser page errors / HTTP 5xx')
 async def screenshot(self,name):
  ARTIFACTS.mkdir(parents=True,exist_ok=True)
  await self.page.screenshot(path=str(ARTIFACTS/name),full_page=True)
 async def axe(self,label):
  path=os.environ.get('AXE_PATH')
  if not path:return
  await self.page.add_script_tag(path=path)
  violations=await self.page.evaluate("async()=>{const r=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa']}});return r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}));}")
  self.assertEqual(violations,[],label+' '+json.dumps(violations,ensure_ascii=False))
 async def address(self):
  await self.page.locator('.address-button').click()
  await self.page.get_by_role('button',name='Preencher com um exemplo fictício').click()
  await self.page.get_by_role('button',name='Salvar endereço').click()
  await self.page.wait_for_function("!document.querySelector('#modal').open")
 async def product(self,slug='casa-do-pao',name='Burger da casa'):
  await self.page.goto(BASE+'#/restaurante/'+slug)
  await self.page.get_by_role('button',name=name,exact=False).click()
 async def test_desktop_core_checkout_persistence_cancel(self):
  await self.address()
  await self.product()
  await self.page.get_by_label('Porção maior').check()
  await self.page.get_by_role('button',name='Aumentar quantidade',exact=True).click()
  await self.page.get_by_role('textbox',name='Alguma observação?').fill('Sem cebola <script> 🥗')
  await self.screenshot('S03-produto-desktop.png')
  await self.axe('product dialog')
  await self.page.get_by_role('button',name='Adicionar',exact=False).click()
  await self.page.locator('.header-cart').click()
  await self.page.get_by_role('heading',name='Seu carrinho',exact=True).wait_for()
  self.assertIn('R$ 69,70',(await self.page.locator('#cart-content').inner_text()).replace('\xa0',' '))
  await self.screenshot('S04-carrinho-desktop.png')
  await self.axe('cart')
  await self.page.get_by_role('button',name='Continuar para o pedido').click()
  await self.page.get_by_role('heading',name='Confira sua boa pedida.').wait_for()
  await self.page.get_by_label('Código do cupom').fill('BEMVINDO10')
  await self.page.get_by_role('button',name='Aplicar',exact=True).click()
  await self.page.get_by_text('BEMVINDO10 aplicado').wait_for()
  self.assertIn('R$ 63,32',(await self.page.locator('.order-summary').inner_text()).replace('\xa0',' '))
  await self.screenshot('S05-checkout-desktop.png')
  await self.axe('checkout')
  await self.page.get_by_role('button',name='Confirmar demonstração').click()
  await self.page.get_by_role('heading',name='Boa escolha. Pedido criado!').wait_for()
  self.assertIn('Sem cebola <script> 🥗',await self.page.locator('main').inner_text())
  order_url=self.page.url
  await self.screenshot('S06-pedido-desktop.png')
  await self.axe('order')
  await self.page.reload()
  await self.page.get_by_role('heading',name='Boa escolha. Pedido criado!').wait_for()
  self.assertEqual(self.page.url,order_url)
  await self.page.get_by_role('button',name='Cancelar pedido de teste').click()
  await self.page.get_by_role('button',name='Confirmar cancelamento').click()
  await self.page.get_by_role('heading',name='Pedido cancelado.').wait_for()
  await self.page.goto(BASE+'#/pedidos')
  await self.page.locator('.history-card').wait_for()
  self.assertIn('Cancelado',await self.page.locator('.history-list').inner_text())
  await self.screenshot('S07-historico-desktop.png')
  await self.axe('history')
 async def test_search_categories_filters_favorites_and_empty(self):
  self.assertEqual(await self.page.locator('.restaurant-card').count(),6)
  await self.page.get_by_role('searchbox',name='Buscar restaurantes ou pratos').fill('pizza')
  self.assertEqual(await self.page.locator('.restaurant-card').count(),1)
  await self.page.get_by_role('searchbox').fill('xyz inexistente')
  await self.page.get_by_role('heading',name='Nenhuma pedida por aqui ainda.').wait_for()
  await self.page.get_by_role('button',name='Limpar filtros').click()
  await self.page.get_by_role('button',name='Entrega grátis',exact=True).click()
  self.assertEqual(await self.page.locator('.restaurant-card').count(),1)
  await self.page.get_by_role('button',name='Entrega grátis',exact=True).click()
  await self.page.get_by_role('button',name='Favoritar Casa do Pão').click()
  await self.page.get_by_role('button',name='♡ Favoritos').click()
  self.assertEqual(await self.page.locator('.restaurant-card').count(),1)
  await self.page.get_by_role('button',name='♡ Favoritos').click()
  await self.page.get_by_role('button',name='Pizza',exact=True).click()
  self.assertEqual(await self.page.locator('.restaurant-card').count(),1)
  await self.page.get_by_role('button',name='Todas as vontades').click()
  await self.page.get_by_label('Ordenar por').select_option('time')
  self.assertIn('Doce Intervalo',await self.page.locator('.restaurant-card').first.inner_text())
  await self.page.get_by_role('button',name='Abertos agora').click()
  self.assertEqual(await self.page.locator('.restaurant-card').count(),5)
 async def test_dialog_keyboard_address_unicode_and_privacy_reset(self):
  await self.page.locator('.address-button').focus()
  await self.page.keyboard.press('Enter')
  await self.page.get_by_role('heading',name='Onde chega sua próxima pedida?').wait_for()
  await self.screenshot('S02-endereco-desktop.png')
  for _ in range(15):
   await self.page.keyboard.press('Tab')
   self.assertTrue(await self.page.evaluate("document.querySelector('#modal').contains(document.activeElement)"))
  await self.page.keyboard.press('Escape')
  self.assertFalse(await self.page.locator('#modal').evaluate('(el)=>el.open'))
  self.assertTrue(await self.page.locator('.address-button').evaluate('(el)=>el===document.activeElement'))
  await self.address()
  await self.page.goto(BASE+'#/ajuda')
  await self.page.get_by_role('button',name='Apagar meus dados de teste').click()
  await self.page.get_by_role('button',name='Apagar meus registros locais').click()
  await self.page.get_by_role('heading',name='Hoje combina').wait_for()
  self.assertIn('Escolha seu endereço',await self.page.locator('#header-address').inner_text())
  await self.page.goto(BASE+'#/ajuda')
  await self.screenshot('S08-ajuda-desktop.png')
  await self.axe('privacy/help')
 async def test_cart_replace_closed_and_unavailable(self):
  await self.product()
  await self.page.get_by_role('button',name='Adicionar',exact=False).click()
  await self.page.wait_for_function("!document.querySelector('#modal').open")
  await self.product('forno-do-bairro','Margherita de forno')
  await self.page.get_by_role('button',name='Adicionar',exact=False).click()
  await self.page.get_by_role('heading',name='Trocar de restaurante?').wait_for()
  await self.page.get_by_role('button',name='Substituir carrinho').click()
  await self.page.wait_for_function("!document.querySelector('#modal').open")
  await self.page.locator('.header-cart').click()
  self.assertIn('Forno do Bairro',await self.page.locator('#cart-content').inner_text())
  self.assertNotIn('Burger da casa',await self.page.locator('#cart-content').inner_text())
  await self.page.keyboard.press('Escape')
  await self.page.goto(BASE+'#/restaurante/casa-do-pao')
  self.assertTrue(await self.page.get_by_role('button',name='Batata crocante').is_disabled())
  await self.page.goto(BASE+'#/restaurante/cantina-da-praca')
  self.assertEqual(await self.page.locator('.product-card:disabled').count(),4)
 async def test_responsive_mobile_core_and_axe(self):
  for width in [360,390,768,1440]:
   await self.page.set_viewport_size({'width':width,'height':844})
   self.assertFalse(await self.page.evaluate('document.documentElement.scrollWidth>innerWidth'),str(width))
   await self.axe('home '+str(width))
  await self.page.set_viewport_size({'width':390,'height':844})
  await self.screenshot('S01-mobile.png')
  await self.address()
  await self.product('verde-e-grao','Bowl da estação')
  await self.page.get_by_role('button',name='Adicionar',exact=False).click()
  await self.page.locator('.mobile-nav button').click()
  await self.axe('mobile cart')
  await self.page.get_by_role('button',name='Continuar para o pedido').click()
  await self.page.get_by_role('heading',name='Confira sua boa pedida.').wait_for()
  self.assertFalse(await self.page.evaluate('document.documentElement.scrollWidth>innerWidth'))
  await self.screenshot('S05-checkout-mobile.png')
  await self.axe('mobile checkout')
  await self.page.get_by_role('button',name='Confirmar demonstração').click()
  await self.page.get_by_role('heading',name='Boa escolha. Pedido criado!').wait_for()
  await self.screenshot('S06-pedido-mobile.png')
  await self.page.set_viewport_size({'width':1440,'height':1000})
  await self.page.goto(BASE+'#/inicio')
  await self.page.get_by_role('heading',name='Hoje combina').wait_for()
  await self.screenshot('S01-desktop.png')
 async def test_offline_retry_and_unknown_route(self):
  await self.context.set_offline(True)
  await self.page.locator('.address-button').click()
  await self.page.get_by_role('button',name='Preencher com um exemplo fictício').click()
  await self.page.get_by_role('button',name='Salvar endereço').click()
  await self.page.locator('.form-error').get_by_text('Sem conexão',exact=False).wait_for()
  await self.context.set_offline(False)
  await self.page.get_by_role('button',name='Salvar endereço').click()
  await self.page.wait_for_function("!document.querySelector('#modal').open")
  await self.page.goto(BASE+'#/inexistente')
  await self.page.get_by_role('heading',name='Essa página não está no cardápio.').wait_for()
if __name__=='__main__':unittest.main(verbosity=2)
