<?php
if($_SERVER['REQUEST_METHOD']!=='POST') redirect('index.php?page=pos');requirePermission('pos');checkCsrf();
$open=openCash($pdo,$_SESSION['user']['id']);if(!$open){flash('error','Abra o caixa antes de vender.');redirect('index.php?page=cash');}$cashId=$open['id'];
$cart=json_decode($_POST['cart_json']??'[]',true);$payments=json_decode($_POST['payments_json']??'[]',true);if(!$cart){flash('error','Carrinho vazio.');redirect('index.php?page=pos');}
$discount=max(0,(float)($_POST['discount']??0));$customer=(int)($_POST['customer_id']??0);$note=trim($_POST['sale_note']??'');
$allowed=['cash','pix','debit','credit','voucher','crediario'];
try{$pdo->beginTransaction();$subtotal=0;$items=[];foreach($cart as $it){$q=max(1,(int)$it['qty']);$ps=$pdo->prepare('SELECT id,name,price,stock FROM products WHERE id=? AND active=1 FOR UPDATE');$ps->execute([(int)$it['id']]);$p=$ps->fetch();if(!$p||$p['stock']<$q) throw new Exception('Estoque insuficiente para '.($p['name']??'produto').'.');$line=$q*(float)$p['price'];$subtotal+=$line;$items[]=[$p,$q,$line];}
$discount=min($discount,$subtotal);$total=round($subtotal-$discount,2);if(!$payments)throw new Exception('Informe pelo menos uma forma de pagamento.');
$normalized=[];$paid=0;$cashPaid=0;$hasCredit=false;foreach($payments as $pay){$m=$pay['method']??'';$a=round(max(0,(float)($pay['amount']??0)),2);if(!in_array($m,$allowed,true)||$a<=0)continue;$inst=max(1,min(24,(int)($pay['installments']??1)));$normalized[]=[$m,$a,$inst];$paid+=$a;if($m==='cash')$cashPaid+=$a;if($m==='crediario')$hasCredit=true;}
if(!$normalized)throw new Exception('Pagamento inválido.');if($hasCredit&&!$customer)throw new Exception('Selecione um cliente para utilizar crediário.');if($paid+0.001<$total)throw new Exception('O valor informado nas formas de pagamento é menor que o total.');$change=max(0,round($paid-$total,2));if($change>0 && $cashPaid+0.001<$change)throw new Exception('Troco só pode ser gerado quando existe pagamento suficiente em dinheiro.');
$primary=$normalized[0][0];$amountReceived=$paid;
$pdo->prepare('INSERT INTO sales(customer_id,user_id,cash_session_id,subtotal,discount,total,payment_method,amount_received,change_amount,status,notes) VALUES(?,?,?,?,?,?,?,?,?,"completed",?)')->execute([$customer?:null,$_SESSION['user']['id'],$cashId,$subtotal,$discount,$total,$primary,$amountReceived,$change,$note?:null]);$saleId=$pdo->lastInsertId();
foreach($items as [$p,$q,$line]){$pdo->prepare('INSERT INTO sale_items(sale_id,product_id,quantity,unit_price,total) VALUES(?,?,?,?,?)')->execute([$saleId,$p['id'],$q,$p['price'],$line]);$pdo->prepare('UPDATE products SET stock=stock-? WHERE id=?')->execute([$q,$p['id']]);$pdo->prepare('INSERT INTO stock_movements(product_id,user_id,type,quantity,reference,notes) VALUES(?,? ,"sale",?,?,?)')->execute([$p['id'],$_SESSION['user']['id'],-$q,'SALE-'.$saleId,'Baixa automática por venda']);}
foreach($normalized as [$m,$a,$inst]){$effective=$a;if($m==='cash'&&$change>0){$effective=max(0,$a-$change);$change=0;}$pdo->prepare('INSERT INTO sale_payments(sale_id,method,amount,installments) VALUES(?,?,?,?)')->execute([$saleId,$m,$effective,$inst]);if($m==='crediario'&&$effective>0){$due=$_POST['credit_due_date']?:date('Y-m-d',strtotime('+30 days'));$pdo->prepare('INSERT INTO accounts_receivable(customer_id,sale_id,description,amount,due_date,status) VALUES(?,?,?,?,?,"open")')->execute([$customer,$saleId,'Crediário venda #'.$saleId,$effective,$due]);}}
audit($pdo,'create','sale',$saleId,'Venda finalizada. Total '.number_format($total,2,'.','').' | '.$note);$pdo->commit();flash('success','Venda #'.$saleId.' finalizada com sucesso.');redirect('index.php?page=sale_view&id='.$saleId);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error',$e->getMessage());redirect('index.php?page=pos');}
