<?php
requirePermission('pos');
$products=$pdo->query("SELECT id,sku,barcode,name,brand,price,stock,category,unit FROM products WHERE active=1 AND stock>0 ORDER BY name")->fetchAll();
$customers=$pdo->query("SELECT id,name,document FROM customers ORDER BY name")->fetchAll();
$openCash=openCash($pdo,$_SESSION['user']['id']);
$title='Frente de Caixa';require __DIR__.'/../../includes/header.php';?>
<div class="page-head"><div><h1>Frente de Caixa</h1><p>PDV rápido com leitor USB/Bluetooth, câmera e múltiplos pagamentos.</p></div><div class="actions"><button type="button" class="btn camera-btn" id="openCameraScanner">📷 Ler código com câmera</button><button type="button" class="btn" id="suspendSale">⏸ Suspender</button><button type="button" class="btn" id="resumeSale">▶ Recuperar</button><span class="badge <?=$openCash?'ok':'danger'?>"><?=$openCash?'Caixa aberto':'Caixa fechado'?></span></div></div>
<?php if(!$openCash):?><div class="alert error">Abra o caixa antes de registrar vendas. <a href="index.php?page=cash">Ir para Caixa</a></div><?php endif;?>
<div class="scanner-strip"><strong>📡 Leitor de código de barras ativo</strong><span>USB/Bluetooth: basta bipar. Câmera: use o botão azul acima. Atalhos: F2 busca · F4 câmera · F8 pagamento · F9 finalizar · Esc limpa busca.</span><span id="scannerStatus" class="badge ok">PRONTO</span></div>
<div class="pos-layout">
<section class="panel pos-products"><div class="search"><input id="productSearch" placeholder="Nome, SKU ou código de barras..." autocomplete="off" autofocus><button type="button" class="btn camera-btn" id="cameraSearchButton">📷 Câmera</button><button type="button" class="btn" id="clearSearch">Limpar</button></div><div id="productGrid" class="product-grid">
<?php foreach($products as $p):?><button type="button" class="product-card" data-search="<?=e(strtolower($p['name'].' '.$p['sku'].' '.$p['barcode'].' '.$p['brand']))?>" data-id="<?=$p['id']?>" data-barcode="<?=e($p['barcode'])?>" data-name="<?=e($p['name'])?>" data-price="<?=$p['price']?>" data-stock="<?=$p['stock']?>"><small><?=e($p['category'])?><?= $p['brand']?' · '.e($p['brand']):'' ?></small><strong><?=e($p['name'])?></strong><span><?=money($p['price'])?></span><em><?=e($p['sku'])?> · Estoque: <?=$p['stock']?> <?=e($p['unit'])?></em></button><?php endforeach;?>
</div></section>
<section class="panel cart-panel"><h2>Cupom de venda</h2><form id="saleForm" method="post" action="index.php?page=sale_create"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="cart_json" id="cartJson"><input type="hidden" name="payments_json" id="paymentsJson"><div id="cartEmpty" class="empty">Nenhum produto adicionado.</div><div id="cartItems"></div><hr><label>Cliente<select name="customer_id" id="customerId"><option value="">Consumidor final</option><?php foreach($customers as $c):?><option value="<?=$c['id']?>"><?=e($c['name'])?><?= $c['document']?' · '.e($c['document']):'' ?></option><?php endforeach;?></select></label><div class="form-grid"><label>Desconto (R$)<input id="discount" name="discount" type="number" step="0.01" min="0" value="0"></label><label>Venc. crediário<input name="credit_due_date" type="date" value="<?=date('Y-m-d',strtotime('+30 days'))?>"></label></div><label>Observação da venda<input name="sale_note" maxlength="255" placeholder="Opcional"></label><div class="total-line"><span>Total</span><strong id="grandTotal">R$ 0,00</strong></div>
<div class="quick-actions"><button type="button" class="btn" data-quick-discount="5">- R$ 5</button><button type="button" class="btn" data-quick-discount="10">- R$ 10</button><button type="button" class="btn" id="clearCart">🗑 Limpar cupom</button></div><div class="payment-box"><div class="panel-head"><h3>Pagamentos</h3><button type="button" class="btn" id="addPayment">+ Forma</button></div><div id="paymentRows"></div><div class="payment-summary"><span>Falta pagar: <strong id="remainingValue">R$ 0,00</strong></span><span>Troco: <strong id="changeValue">R$ 0,00</strong></span></div></div>
<button class="btn primary wide big-btn" <?=$openCash?'':'disabled'?>>Finalizar venda</button></form></section>
</div>
<div class="modal" id="cameraModal" hidden><div class="modal-card"><div class="panel-head"><div><h2>Leitor pela câmera</h2><p>Aponte a câmera para EAN-8, EAN-13, UPC ou Code 128.</p></div><button type="button" class="btn" id="closeCameraScanner">Fechar</button></div><video id="barcodeVideo" playsinline muted></video><div id="cameraMessage" class="scanner-message">Inicializando câmera...</div></div></div>
<script>window.DREAMLAST_PRODUCTS=<?=json_encode($products,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;</script>
<?php require __DIR__.'/../../includes/footer.php';?>
