USE dreamlast_pdv;
ALTER TABLE users MODIFY role ENUM('admin','manager','cashier') NOT NULL DEFAULT 'cashier';
ALTER TABLE sales MODIFY payment_method ENUM('cash','pix','debit','credit','voucher','crediario') NOT NULL;
ALTER TABLE sales MODIFY status ENUM('completed','partially_returned','returned','cancelled') NOT NULL DEFAULT 'completed';
CREATE TABLE IF NOT EXISTS suppliers (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(160) NOT NULL,document VARCHAR(30),contact VARCHAR(120),phone VARCHAR(30),email VARCHAR(160),address TEXT,active TINYINT(1) DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(name),INDEX(document)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS purchases (id INT AUTO_INCREMENT PRIMARY KEY,supplier_id INT NOT NULL,user_id INT NOT NULL,invoice_number VARCHAR(80),total DECIMAL(12,2) NOT NULL DEFAULT 0,status ENUM('received','cancelled') DEFAULT 'received',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(supplier_id) REFERENCES suppliers(id),FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS purchase_items (id INT AUTO_INCREMENT PRIMARY KEY,purchase_id INT NOT NULL,product_id INT NOT NULL,quantity INT NOT NULL,unit_cost DECIMAL(12,2) NOT NULL,total DECIMAL(12,2) NOT NULL,FOREIGN KEY(purchase_id) REFERENCES purchases(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS accounts_payable (id INT AUTO_INCREMENT PRIMARY KEY,supplier_id INT NULL,purchase_id INT NULL,description VARCHAR(180) NOT NULL,amount DECIMAL(12,2) NOT NULL,due_date DATE NOT NULL,status ENUM('open','paid','cancelled') DEFAULT 'open',paid_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(supplier_id) REFERENCES suppliers(id),FOREIGN KEY(purchase_id) REFERENCES purchases(id),INDEX(due_date),INDEX(status)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS accounts_receivable (id INT AUTO_INCREMENT PRIMARY KEY,customer_id INT NULL,sale_id INT NULL,description VARCHAR(180) NOT NULL,amount DECIMAL(12,2) NOT NULL,due_date DATE NOT NULL,status ENUM('open','received','cancelled') DEFAULT 'open',received_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(customer_id) REFERENCES customers(id),FOREIGN KEY(sale_id) REFERENCES sales(id),INDEX(due_date),INDEX(status)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS quotes (id INT AUTO_INCREMENT PRIMARY KEY,customer_id INT NULL,user_id INT NOT NULL,subtotal DECIMAL(12,2) NOT NULL,discount DECIMAL(12,2) NOT NULL DEFAULT 0,total DECIMAL(12,2) NOT NULL,valid_until DATE NOT NULL,status ENUM('open','approved','expired','cancelled') DEFAULT 'open',notes TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(customer_id) REFERENCES customers(id),FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS quote_items (id INT AUTO_INCREMENT PRIMARY KEY,quote_id INT NOT NULL,product_id INT NOT NULL,quantity INT NOT NULL,unit_price DECIMAL(12,2) NOT NULL,total DECIMAL(12,2) NOT NULL,FOREIGN KEY(quote_id) REFERENCES quotes(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS sale_returns (id INT AUTO_INCREMENT PRIMARY KEY,sale_id INT NOT NULL,user_id INT NOT NULL,type ENUM('return','cancel') NOT NULL,total DECIMAL(12,2) NOT NULL DEFAULT 0,reason VARCHAR(255) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(sale_id) REFERENCES sales(id),FOREIGN KEY(user_id) REFERENCES users(id),INDEX(created_at)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS sale_return_items (id INT AUTO_INCREMENT PRIMARY KEY,return_id INT NOT NULL,product_id INT NOT NULL,quantity INT NOT NULL,unit_price DECIMAL(12,2) NOT NULL,total DECIMAL(12,2) NOT NULL,FOREIGN KEY(return_id) REFERENCES sale_returns(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id)) ENGINE=InnoDB;
INSERT INTO suppliers(name,document,contact,phone,email)
SELECT 'Fornecedor Exemplo','12.345.678/0001-99','Comercial','(11) 4000-0000','fornecedor@exemplo.com'
WHERE NOT EXISTS (SELECT 1 FROM suppliers LIMIT 1);
