<?php
return [
    'pdv' => [
        'slug'=>'pdv', 'number'=>'01', 'name'=>'Dream Last PDV Pro', 'short'=>'PDV Pro',
        'category'=>'Vendas & caixa', 'headline'=>'Do balcão ao controle da operação.',
        'description'=>'Frente de caixa completa para comércio, com estoque, vendas, pagamentos, clientes, fornecedores, compras, caixa, relatórios e leitura de código de barras por leitor ou câmera.',
        'summary'=>'Um ponto de venda que reúne atendimento, pagamentos e estoque na mesma operação.',
        'challenge'=>'Acompanhar uma venda exige mais do que registrar um pagamento. Produtos, estoque, caixa e histórico precisam permanecer conectados, inclusive em devoluções e vendas com diferentes formas de pagamento.',
        'solution'=>'O PDV conecta a frente de caixa ao cadastro de produtos, às movimentações de estoque e ao financeiro. Leitores físicos e câmera ajudam na identificação dos itens; atalhos de teclado agilizam a operação.',
        'features'=>['Scanner de código de barras por leitor ou câmera','Múltiplos pagamentos e parcelas de cartão','Abertura, movimentações e fechamento de caixa','Estoque, inventário e histórico de movimentações','Clientes, fornecedores, compras e relatórios','Orçamentos, devoluções e suspensão de vendas'],
        'technologies'=>['PHP','MySQL','JavaScript'],
        'result'=>'Uma demonstração navegável de gestão comercial: da leitura do produto ao comprovante, com vendas, caixa e estoque integrados. Os dados exibidos são de demonstração, sem métricas de clientes ou de desempenho comercial.',
        'screen'=>'Frente de caixa', 'detail_screen'=>'Produtos e estoque',
    ],
    'erp' => [
        'slug'=>'erp', 'number'=>'02', 'name'=>'Dream Last ERP', 'short'=>'ERP',
        'category'=>'Gestão empresarial', 'headline'=>'Uma visão integrada do negócio.',
        'description'=>'Centralize as principais rotinas da empresa em um ERP demonstrativo com clientes, fornecedores, estoque, compras, vendas, financeiro, funcionários e indicadores.',
        'summary'=>'Compras, vendas, estoque e financeiro conectados para acompanhar o dia a dia da empresa.',
        'challenge'=>'Informações distribuídas entre cadastros, compras e financeiro dificultam acompanhar a operação. Uma venda deve atualizar o estoque e refletir no controle financeiro, sem perder o histórico.',
        'solution'=>'O ERP centraliza as rotinas em módulos relacionados, com dashboard executivo, cadastros e relatórios. Compras e vendas movimentam o estoque e geram lançamentos financeiros.',
        'features'=>['Dashboard com KPIs e indicadores','Clientes, fornecedores e produtos','Compras e vendas integradas','Financeiro e saldo projetado','Estoque e movimentações automáticas','Funcionários, relatórios e gráficos'],
        'technologies'=>['PHP','MySQL','Bootstrap','Chart.js'],
        'result'=>'Uma base funcional para explorar a gestão de uma empresa em um único ambiente. A demonstração reúne cadastros, movimentações e indicadores com dados de exemplo, sem atribuir resultados a empresas reais.',
        'screen'=>'Dashboard executivo', 'detail_screen'=>'Clientes',
    ],
    'crm' => [
        'slug'=>'crm', 'number'=>'03', 'name'=>'Dream Last CRM', 'short'=>'CRM',
        'category'=>'Relacionamento & vendas', 'headline'=>'Cada relacionamento, no seu contexto.',
        'description'=>'Organize leads, clientes, oportunidades e atendimento em um CRM corporativo pensado para acompanhar o relacionamento comercial do primeiro contato ao pós-venda.',
        'summary'=>'Leads, oportunidades e atendimento organizados do primeiro contato ao pós-venda.',
        'challenge'=>'Uma equipe comercial precisa acompanhar contatos, oportunidades e próximos passos. Depois da venda, projetos e solicitações de atendimento também fazem parte desse relacionamento.',
        'solution'=>'O CRM reúne clientes, leads, oportunidades, agenda e tarefas. Módulos de projetos e tickets estendem o acompanhamento, com perfis de acesso e registros de auditoria.',
        'features'=>['Pipeline comercial e oportunidades','Leads, clientes e histórico comercial','Tarefas e agenda','Projetos e tickets de atendimento','Perfis de acesso e auditoria','Financeiro e relatórios'],
        'technologies'=>['PHP','MySQL','JavaScript'],
        'result'=>'Uma demonstração corporativa com navegação entre relacionamento, vendas e atendimento. Os registros são exemplos do próprio projeto; não representam clientes ou resultados comerciais da Dream Last.',
        'screen'=>'Visão geral', 'detail_screen'=>'Pipeline de oportunidades',
    ],
];
