<?php
$title='Dashboard';
$today=$pdo->query("SELECT COALESCE(SUM(s.total-COALESCE(r.ret,0)),0) FROM sales s LEFT JOIN (SELECT sale_id,SUM(total) ret FROM sale_returns GROUP BY sale_id) r ON r.sale_id=s.id WHERE DATE(s.created_at)=CURDATE() AND s.status IN ('completed','partially_returned')")->fetchColumn();
$count=$pdo->query("SELECT COUNT(*) FROM sales WHERE DATE(created_at)=CURDATE() AND status IN ('completed','partially_returned')")->fetchColumn();
$products=$pdo->query('SELECT COUNT(*) FROM products WHERE active=1')->fetchColumn();$low=$pdo->query('SELECT COUNT(*) FROM products WHERE active=1 AND stock<=min_stock')->fetchColumn();
$payable=$pdo->query("SELECT COALESCE(SUM(amount),0) FROM accounts_payable WHERE status='open' AND due_date<=DATE_ADD(CURDATE(),INTERVAL 7 DAY)")->fetchColumn();
$receivable=$pdo->query("SELECT COALESCE(SUM(amount),0) FROM accounts_receivable WHERE status='open'")->fetchColumn();
$recent=$pdo->query("SELECT s.id,s.total,s.payment_method,s.status,s.created_at,c.name customer,u.name seller FROM sales s LEFT JOIN customers c ON c.id=s.customer_id JOIN users u ON u.id=s.user_id ORDER BY s.id DESC LIMIT 8")->fetchAll();require __DIR__.'/../../includes/header.php'; ?>
<div class="page-head"><div><h1>Dashboard</h1><p>Resumo operacional, financeiro e de estoque.</p></div><?php if(can('pos')):?><a class="btn primary" href="index.php?page=pos">+ Nova venda</a><?php endif;?></div>
<div class="cards"><div class="stat"><small>Faturamento líquido hoje</small><strong><?=money($today)?></strong><span><?=$count?> atendimento(s)</span></div><div class="stat"><small>Estoque baixo</small><strong><?=$low?></strong><span>de <?=$products?> produtos ativos</span></div><div class="stat"><small>A receber</small><strong><?=money($receivable)?></strong><span>crediário em aberto</span></div><div class="stat"><small>A pagar em 7 dias</small><strong><?=money($payable)?></strong><span>compromissos próximos</span></div></div>
<section class="panel"><div class="panel-head"><h2>Últimas vendas</h2></div><div class="table-wrap"><table><thead><tr><th>#</th><th>Cliente</th><th>Vendedor</th><th>Pagamento</th><th>Status</th><th>Total</th><th>Data</th></tr></thead><tbody><?php foreach($recent as $r):?><tr><td><a href="index.php?page=sale_view&id=<?=$r['id']?>">#<?=$r['id']?></a></td><td><?=e($r['customer']?:'Consumidor final')?></td><td><?=e($r['seller'])?></td><td><?=e(paymentLabel($r['payment_method']))?></td><td><span class="badge <?=$r['status']==='completed'?'ok':'danger'?>"><?=e($r['status'])?></span></td><td><?=money($r['total'])?></td><td><?=date('d/m/Y H:i',strtotime($r['created_at']))?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php require __DIR__.'/../../includes/footer.php'; ?>
